<?php

namespace Database\Seeders;

use App\Enums\StatusEnum;
use App\Models\Currency;
use App\Models\Store;
use Illuminate\Database\Seeder;

class StoreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $stores = [
            [
                'name' => 'Amazon UAE',
                'domain' => 'amazon.ae',
                'image' => 'amazon_ae.png',
                'currency_id' => Currency::firstOrCreate(['code' => 'AED'])->id,
                'slug' => 'amazon_ae',
            ],
            [
                'name' => 'Amazon USA',
                'domain' => 'amazon.com',
                'image' => 'amazon.png',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'amazon_com',
            ],
            [
                'name' => 'Amazon UK',
                'domain' => 'amazon.co.uk',
                'image' => 'amazon_co_uk.png',
                'currency_id' => Currency::firstOrCreate(['code' => '£'])->id,
                'slug' => 'amazon_uk',
            ],
            [
                'name' => 'Amazon Germany',
                'domain' => 'amazon.de',
                'image' => 'amazon_de.png',
                'currency_id' => Currency::firstOrCreate(['code' => '€'])->id,
                'slug' => 'amazon_de',
            ],
            [
                'name' => 'Amazon France',
                'domain' => 'amazon.fr',
                'image' => 'amazon_fr.png',
                'currency_id' => Currency::firstOrCreate(['code' => '€'])->id,
                'slug' => 'amazon_fr',
            ],
            [
                'name' => 'Amazon Italy',
                'domain' => 'amazon.it',
                'image' => 'amazon_it.png',
                'currency_id' => Currency::firstOrCreate(['code' => '€'])->id,
                'slug' => 'amazon_it',
            ],
            [
                'name' => 'Amazon Saudi Arabia',
                'domain' => 'amazon.sa',
                'image' => 'amazon_sa.png',
                'currency_id' => Currency::firstOrCreate(['code' => 'SAR'])->id,
                'slug' => 'amazon_sa',
            ],
            [
                'name' => 'Amazon Spain',
                'domain' => 'amazon.es',
                'image' => 'amazon_es.png',
                'currency_id' => Currency::firstOrCreate(['code' => '€'])->id,
                'slug' => 'amazon_es',
            ],
            [
                'name' => 'Amazon Poland',
                'domain' => 'amazon.pl',
                'image' => 'amazon_pl.png',
                'currency_id' => Currency::firstOrCreate(['code' => 'zł'])->id,
                'slug' => 'amazon_pl',
            ],
            [
                'name' => 'Amazon Turkey',
                'domain' => 'amazon.com.tr',
                'image' => 'amazon_com_tr.png',
                'currency_id' => Currency::firstOrCreate(['code' => 'TL'])->id,
                'slug' => 'amazon_com_tr',
            ],
            [
                'name' => 'Amazon Australia',
                'domain' => 'amazon.com.au',
                'image' => 'amazon_com_au.png',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'amazon_com_au',
            ],
            [
                'name' => 'Amazon Brazil',
                'domain' => 'amazon.com.br',
                'image' => 'amazon_com_br.png',
                'currency_id' => Currency::firstOrCreate(['code' => 'R$'])->id,
                'slug' => 'amazon_com_br',
            ],
            [
                'name' => 'Amazon Canada',
                'domain' => 'amazon.ca',
                'image' => 'amazon_ca.png',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'amazon_ca',
            ],
            [
                'name' => 'Amazon China',
                'domain' => 'amazon.cn',
                'image' => 'amazon.png',
                'currency_id' => Currency::firstOrCreate(['code' => '¥'])->id,
                'slug' => 'amazon_tr',
            ],
            [
                'name' => 'Amazon Egypt',
                'domain' => 'amazon.eg',
                'image' => 'amazon_eg.png',
                'currency_id' => Currency::firstOrCreate(['code' => 'EGP'])->id,
                'slug' => 'amazon_eg',
            ],
            [
                'name' => 'Amazon Japan',
                'domain' => 'amazon.co.jp',
                'image' => 'amazon_co_jp.png',
                'currency_id' => Currency::firstOrCreate(['code' => '¥'])->id,
                'slug' => 'amazon_co_jp',
            ],
            [
                'name' => 'Amazon India',
                'domain' => 'amazon.in',
                'image' => 'amazon_in.png',
                'currency_id' => Currency::firstOrCreate(['code' => '₹'])->id,
                'slug' => 'amazon_in',
            ],
            [
                'name' => 'Amazon Mexicon',
                'domain' => 'amazon.com.mx',
                'image' => 'amazon_com_mx.png',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'amazon_com_mx',
            ],
            [
                'name' => 'Amazon Netherlands',
                'domain' => 'amazon.nl',
                'image' => 'amazon_nl.png',
                'currency_id' => Currency::firstOrCreate(['code' => '€'])->id,
                'slug' => 'amazon_nl',
            ],
            [
                'name' => 'Amazon Singapore',
                'domain' => 'amazon.sg',
                'image' => 'amazon_sg.png',
                'currency_id' => Currency::firstOrCreate(['code' => 'S$'])->id,
                'slug' => 'amazon_sg',
            ],
            [
                'name' => 'Amazon Sweden',
                'domain' => 'amazon.se',
                'image' => 'amazon_se.png',
                'currency_id' => Currency::firstOrCreate(['code' => 'kr'])->id,
                'slug' => 'amazon_se',
            ],
            [
                'name' => 'Amazon Belgium',
                'domain' => 'amazon.com.be',
                'image' => 'amazon.png',
                'currency_id' => Currency::firstOrCreate(['code' => '€'])->id,
                'slug' => 'amazon_com_be',
            ],
            [
                'name' => 'Argos UK',
                'domain' => 'argos.co.uk',
                'image' => 'argos.png',
                'currency_id' => Currency::firstOrCreate(['code' => '£'])->id,
                'slug' => 'argos_co_uk',
            ],
            [
                'name' => 'DIY',
                'domain' => 'diy.com',
                'image' => 'diy_com.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '£'])->id,
                'slug' => 'diy_com',
            ],
            [
                'name' => 'Ebay',
                'domain' => 'ebay.com',
                'image' => 'ebay.png',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'ebay_com',
            ],
            [
                'name' => 'Fnac',
                'domain' => 'fnac.com',
                'image' => 'fnac_com.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '£'])->id,
                'slug' => 'fnac_com',
            ],
            [
                'name' => 'Target',
                'domain' => 'target.com',
                'image' => 'target.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'target_com',
            ],
            [
                'name' => 'Walmart USA',
                'domain' => 'walmart.com',
                'image' => 'walmart.png',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'walmart_com',
            ],
            [
                'name' => 'Walmart Canada',
                'domain' => 'walmart.ca',
                'image' => 'walmart.png',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'walmart_ca',
            ],
            [
                'name' => 'Noon UAE',
                'domain' => 'noon.com',
                'image' => 'noon.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'AED'])->id,
                'slug' => 'noon_com',
            ],
            [
                'name' => 'Noon Egypt',
                'domain' => 'noon.com',
                'image' => 'noon.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'EGP'])->id,
                'slug' => 'noon_com',
            ],
            [
                'name' => 'Noon Saudi',
                'domain' => 'noon.com',
                'image' => 'noon.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'SAR'])->id,
                'slug' => 'noon_com',
            ],
            [
                'name' => 'Costco',
                'domain' => 'costco.com',
                'image' => 'costco.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'costco_com',
            ],
            [
                'name' => 'Costco Australia',
                'domain' => 'costco.com.au',
                'image' => 'costco.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'costco_com_au',
            ],
            [
                'name' => 'Costco Canada',
                'domain' => 'costco.ca',
                'image' => 'costco.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'costco_ca',
            ],
            [
                'name' => 'Costco Iceland',
                'domain' => 'costco.is',
                'image' => 'costco.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'kr'])->id,
                'slug' => 'costco_is',
            ],
            [
                'name' => 'Costco Japan',
                'domain' => 'costco.co.jp',
                'image' => 'costco.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '¥'])->id,
                'slug' => 'costco_co_jp',
            ],
            [
                'name' => 'Costco Korea',
                'domain' => 'costco.co.kr',
                'image' => 'costco.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '원'])->id,
                'slug' => 'costco_co_kr',
            ],
            [
                'name' => 'Costco Mexico',
                'domain' => 'costco.com.mx',
                'image' => 'costco.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'costco_com_mx',
            ],
            [
                'name' => 'Costco Taiwan',
                'domain' => 'costco.com.tw',
                'image' => 'costco.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'costco_com_tw',
            ],
            [
                'name' => 'Costco UK',
                'domain' => 'costco.co.uk',
                'image' => 'costco.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '£'])->id,
                'slug' => 'costco_co_uk',
            ],
            [
                'name' => 'Currys',
                'domain' => 'currys.co.uk',
                'image' => 'currys.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '£'])->id,
                'slug' => 'currys_co_uk',
            ],
            [
                'name' => 'Canadian Tire',
                'domain' => 'canadiantire.ca',
                'image' => 'canadiantire.png',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'canadiantire_ca',
            ],
            [
                'name' => 'Princess Auto',
                'domain' => 'princessauto.com',
                'image' => 'princessauto.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'princessauto_com',
            ],
            [
                'name' => 'Media Market Spain',
                'domain' => 'mediamarkt.es',
                'image' => 'mediamarkt.png',
                'currency_id' => Currency::firstOrCreate(['code' => '€'])->id,
                'slug' => 'mediamarkt_es',
            ],
            [
                'name' => 'Media Markt Belgium',
                'domain' => 'mediamarkt.be',
                'image' => 'mediamarkt.png',
                'currency_id' => Currency::firstOrCreate(['code' => '€'])->id,
                'slug' => 'mediamarkt_be',
            ],
            [
                'name' => 'Best Buy',
                'domain' => 'bestbuy.com',
                'image' => 'bestbuy.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'bestbuy_com',
            ],
            [
                'name' => 'Best Buy Canada',
                'domain' => 'bestbuy.ca',
                'image' => 'bestbuy.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'bestbuy_ca',
            ],
            [
                'name' => 'Emax UAE',
                'domain' => 'emaxme.com',
                'image' => 'emax.png',
                'currency_id' => Currency::firstOrCreate(['code' => 'AED'])->id,
                'slug' => 'uae_emaxme_com',
                'status' => StatusEnum::Disabled,
            ],
            [
                'name' => 'Ebay Germany',
                'domain' => 'ebay.de',
                'image' => 'ebay.png',
                'currency_id' => Currency::firstOrCreate(['code' => '€'])->id,
                'slug' => 'ebay_de',
            ],
            [
                'name' => 'FlipKart',
                'domain' => 'flipkart.com',
                'image' => 'flipkart.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '₹'])->id,
                'slug' => 'flipkart_com',
            ],
            [
                'name' => 'Myntra',
                'domain' => 'myntra.com',
                'image' => 'myntra.png',
                'currency_id' => Currency::firstOrCreate(['code' => '₹'])->id,
                'slug' => 'myntra_com',
            ],
            [
                'name' => 'Snapdeal',
                'domain' => 'snapdeal.com',
                'image' => 'snapdeal.png',
                'currency_id' => Currency::firstOrCreate(['code' => '₹'])->id,
                'slug' => 'snapdeal_com',
            ], [
                'name' => 'Nykaa',
                'domain' => 'nykaa.com',
                'image' => 'nykaa.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '₹'])->id,
                'slug' => 'nykaa_com',
            ], [
                'name' => 'Tata Cliq',
                'domain' => 'tatacliq.com',
                'image' => 'tatacliq.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '₹'])->id,
                'slug' => 'tatacliq_com',
            ], [
                'name' => 'Ajio',
                'domain' => 'ajio.com',
                'image' => 'ajio.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '₹'])->id,
                'slug' => 'ajio_com',
            ], [
                'name' => 'Newegg USA',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Argentina',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Australia',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Bahrain',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'BHD'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Canada',
                'domain' => 'newegg.ca',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Hong Kong',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Occupied Palestine',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '₪'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Japan',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '¥'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Kuwait',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'KWD'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Mexico',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg New Zealand',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Oman',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'OMR'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Philippines',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '₱'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Qatar',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'QAR'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Saudi Arabia',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'SAR'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Singapore',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg South Korea',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '₩'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg Thailand',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '฿'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg UAE',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'AED'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Newegg UK',
                'domain' => 'newegg.com',
                'image' => 'newegg.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '£'])->id,
                'slug' => 'newegg_com',
            ], [
                'name' => 'Microless UAE',
                'domain' => 'microless.com',
                'image' => 'microless.svg',
                'currency_id' => Currency::firstOrCreate(['code' => 'AED'])->id,
                'slug' => 'microless_com',
            ], [
                'name' => 'Microless Global',
                'domain' => 'microless.com',
                'image' => 'microless.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '$'])->id,
                'slug' => 'microless_com',
            ], [
                'name' => 'Next Hardware & Software',
                'domain' => 'nexths.it',
                'image' => 'microless.svg',
                'currency_id' => Currency::firstOrCreate(['code' => '€'])->id,
                'slug' => 'nexths_it',
            ],
        ];

        foreach ($stores as $store) {
            Store::updateOrCreate([
                'domain' => $store["domain"],
                'name' => $store["name"],
                "currency_id" => $store["currency_id"],
            ],
                $store
            );
        }
    }
}
