version: '3.8'

networks:
    discount-bandit:
        driver: bridge

services:
    discount-bandit:
        image: cybrarist/discount-bandit:v3-test
        ports:
            - 8080:80
        networks:
            - discount-bandit
        environment:
            DB_HOST: discount-bandit-mysql
            DEFAULT_USER: "test"
            DEFAULT_EMAIL: "docker@test.com"
            DEAFULT_PASSWORD: "thisismypassword"
            NTFY_LINK: "https://ntfy.sh/test"
            NTFY_USER : "ntfy_user"
            NTFY_PASSWORD : "ntfy_password"
            NTFY_TOKEN : ""
        depends_on:
            mysql :
                condition: service_healthy

    mysql:
        image: mysql:8.2.0
        container_name: discount-bandit-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: discount-bandit
            MYSQL_USER: bandit
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            SERVICE_NAME: mysql
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 1s
            retries: 10
        networks:
            - discount-bandit
