<?php

namespace App\Filament\Pages\Auth;

use App\Models\User;

class Login extends \Filament\Auth\Pages\Login
{
    public function mount(): void
    {
        if (! User::exists()) {
            redirect()->to('/register');
        }

        parent::mount(); // TODO: Change the autogenerated stub
    }
}
