<?php

namespace App\Filament\Pages\Auth;

use App\Enums\RoleEnum;
use App\Models\User;
use Filament\Actions\Action;
use Filament\Forms\Components\Placeholder;

class Register extends \Filament\Auth\Pages\Register
{

    public function mount(): void
    {
        if (User::exists()) {
            redirect()->to('/login');
        }

        parent::mount(); // TODO: Change the autogenerated stub
    }

    public function getRegisterFormAction(): Action
    {
        if (User::count() > 0) {
            return Action::make('redirect')
                ->action(fn () => redirect()->to('/'));
        }

        return parent::getRegisterFormAction();
    }

    protected function mutateFormDataBeforeRegister(array $data): array
    {
        $data['role'] = RoleEnum::Admin->value;

        return parent::mutateFormDataBeforeRegister($data);
    }

    protected function getForms(): array
    {
        if (User::count() == 0) {
            $fields = [
                $this->getNameFormComponent(),
                $this->getEmailFormComponent(),
                $this->getPasswordFormComponent(),
                $this->getPasswordConfirmationFormComponent(),
            ];
        }

        return [
            'form' => $this->form(
                $this->makeForm()
                    ->schema($fields)
                    ->statePath('data'),
            ),
        ];
    }
}
